version: '3'

volumes:
  pgdata:
    driver: local
  dbdump:
    driver: local
  solrdata:
    driver: local
  rabbitdata:
    driver: local

services:
  db:
    build:
      context: postgres-dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-9.5}
    image: musicbrainz-docker_db:${POSTGRES_VERSION:-9.5}
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - metabrainz

  musicbrainz:
    build:
      context: musicbrainz-dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-9.5}
    volumes:
      - dbdump:/media/dbdump
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    environment:
    depends_on:
      - db
      - redis
    networks:
      - metabrainz

  solr:
    image: ta264/musicbrainz-solr
    restart: unless-stopped
    volumes:
      - solrdata:/opt/solr/server/solr/data
    ports:
      - "8983:8983"
    networks:
      - metabrainz

  sir:
    build:
        context: sir-dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - rabbit
      - solr
    networks:
      - metabrainz

  rabbit:
    image: rabbitmq:3.6
    restart: unless-stopped
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "abc"
      RABBITMQ_DEFAULT_PASS: "abc"
    volumes:
      - rabbitdata:/var/lib/rabbitmq/mnesia
    networks:
      - metabrainz

  redis:
    image: redis:3-alpine
    restart: unless-stopped
    networks:
      - metabrainz

networks:
  metabrainz:
